export const BEHAVIOR_QUESTION_TYPES = [
  'GENERAL',
  'FREQUENCY',
  'POINT_OF_PURCHASE',
  'DEFAULT'
];

export const CUSTOM_BEHAVIOR_QUESTION_TYPES = [
  'GENERAL',
  'FREQUENCY',
  'POINT_OF_PURCHASE',
  'CUSTOM',
  'DEFAULT'
];
